/*
 * JSP generated by Resin-3.0.14 (built Tue, 05 Jul 2005 11:03:36 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import de.jose.Application;
import de.jose.pgn.Collection;
import de.jose.web.SessionUtil;
import de.jose.db.JoConnection;
import de.jose.db.JoPreparedStatement;
import java.sql.ResultSet;
import de.jose.pgn.PgnUtil;
import de.jose.pgn.PgnDate;
import java.util.Date;
import de.jose.db.JoStatement;
import de.jose.web.WebApplication;
import de.jose.pgn.SearchRecord;
import java.util.ArrayList;
import de.jose.db.ParamStatement;
import de.jose.view.ListPanel;
import de.jose.util.map.IntHashSet;
import de.jose.Language;
import de.jose.Util;
import de.jose.util.StringUtil;

public class _collection__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;

  
  	protected boolean setStringField(SessionUtil su, SearchRecord search, String fieldName)
  	{
  		String oldValue = (String)search.getField(fieldName);
  		if (oldValue==null)
  			oldValue="";
  		else
  			oldValue = oldValue.trim();
  		String newValue = su.getString(fieldName,oldValue,true);
  		if (newValue==null)
  			newValue="";
  		else
  			newValue = newValue.trim();
  
  		search.setField(fieldName,newValue);
  
  		return ! oldValue.equals(newValue);
  	}

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	WebApplication.open(application,response);
	SessionUtil su = new SessionUtil(request,session);

	int count_results = su.getInt("count-results",-1,true);

	//  get search record
	SearchRecord search = (SearchRecord)su.get("search-record",true);
	if (search==null) {
		search = new SearchRecord();
		search.clear();
		search.collections = new IntHashSet();
		search.collections.add(1001);
		search.adapter = JoConnection.getAdapter();
		search.sortOrder = ListPanel.COL_IDX+1;   //  negative values sort descending
		su.set("search-record",search);
		count_results = -1;
	}

	//  get URL parameters: CId, Name, page, pagesize, sort
	int cid = su.getInt("CId",0,false);
	//  try name ?
	String name = su.getString("Name",false);
	if (cid <= 0 && name!=null)
		cid = Collection.getId(name,false);

	if (cid>0) {
		if (cid != su.getInt("CId",1001,true))  search.clear();
		search.collections.clear();
		search.collections.add(cid);
		count_results = -1;
	}
	else
		cid = su.getInt("CId",1001,true);
	su.set("CId",cid);

	search.sortOrder = su.getInt("sort",search.sortOrder,false);

	int pagenum = su.getInt("pagenum",1,true);
	int pagesize = su.getInt("pagesize",20,true);
	if (pagesize < 1) pagesize=1;
	if (pagesize > 500) pagesize=500;

	//  edit search record
	boolean big_search = su.getBoolean("big-search",false,true);
	if (su.wasSubmitted("more-search")) big_search=!big_search;
	su.set("big-search",big_search);

	boolean dirty = setStringField(su,search,"firstPlayerName");

	if (dirty) {
		//  if search was modified
		pagenum = 1;
		count_results = -1;
	}

	ArrayList input_errors = new ArrayList();
	SearchRecord work_search = (SearchRecord)search.clone();
	work_search.finish(input_errors);	//	check plausability
	su.set("work-search",work_search);

	//  estimate results
	if (count_results < 0) count_results = work_search.estimateResults();

	if (count_results >= 0) {
		int max_page = (count_results+pagesize-1)/pagesize;
		if (pagenum > max_page) pagenum = max_page;
	}
	if (pagenum<1) pagenum=1;

	su.set("pagenum",pagenum);
	su.set("pagesize",pagesize);

	//  make the query
	JoConnection conn = null;
	JoPreparedStatement stm = null;
	ResultSet res = null;

	try {
		conn = JoConnection.get();

		int row0 = (pagenum-1)*pagesize;
		int[] id_array = new int[pagesize+1];

		su.set("current-row0",row0);
		su.set("current-ids",id_array);

		ParamStatement pstm = work_search.makeDataStatement(row0,id_array.length);

		stm = pstm.execute(conn,ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		res = stm.getResultSet();

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((search.sortOrder));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((search.toggleSortOrder(ListPanel.COL_IDX+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.index")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_IDX+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_IDX+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((search.toggleSortOrder(ListPanel.COL_WNAME+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.white.name")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_WNAME+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_WNAME+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((search.toggleSortOrder(ListPanel.COL_WELO+1)));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
				if (search.sortOrder==+(ListPanel.COL_WELO+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_WELO+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((search.toggleSortOrder(ListPanel.COL_BNAME+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.black.name")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_BNAME+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_BNAME+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_BELO+1)));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
				if (search.sortOrder==+(ListPanel.COL_BELO+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_BELO+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_RESULT+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.result")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_RESULT+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_RESULT+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_EVENT+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.event")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_EVENT+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_EVENT+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_SITE+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.site")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_SITE+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_SITE+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_ROUND+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.round")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_ROUND+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_ROUND+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_DATE+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.date")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_DATE+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_DATE+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((search.toggleSortOrder(ListPanel.COL_OPENING+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Language.get("column.game.opening")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
				if (search.sortOrder==+(ListPanel.COL_OPENING+1)) {
					
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
				}
				else if (search.sortOrder==-(ListPanel.COL_OPENING+1)) {
					
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
				}
		
      out.write(_jsp_string10, 0, _jsp_string10.length);
      
		int row = (pagenum-1)*pagesize;
		int max_row = pagenum*pagesize;

		for ( ; (row < max_row) && res.next(); row++)
		{
			id_array[row-row0] = res.getInt(1);

			String row_style = ((row %2)==1) ? "odd":"even";
			int gid = res.getInt(1/*Game.Id*/);

			String white_title = res.getString(5/*WhiteTitle*/);
			String white_name = res.getString(4/*White.Name*/);
			if (white_title!=null) white_name = white_title+" "+white_name;

			String white_elo = res.getString(6/*WhiteELO*/);
			if (white_elo==null || white_elo.equals("0")) white_elo = "";

			String black_title = res.getString(8/*BlackTitle*/);
			String black_name = res.getString(7/*Black.Name*/);
			if (black_title!=null) black_name = black_title+" "+black_name;

			String black_elo = res.getString(9/*BlackELO*/);
			if (black_elo==null || black_elo.equals("0")) black_elo = "";

			String event_name = res.getString(11/*Event.Name*/);
			if (event_name==null) event_name = "";

			String site_name = res.getString(12/*Site.Name*/);
			if (site_name==null) site_name = "";

			String round = res.getString(13/*Round*/);
			String board = res.getString(14/*Board*/);
			if (round==null && board==null)
				round = "";
			else if (board==null)
				 ;
			else if (round==null)
				round = board;
			else
				round = round+" "+board;

			String eco = res.getString(16/*Game.ECO*/);
			String opening = res.getString(17/*Opening.Name*/);
			if (eco==null && opening==null)
				opening = "";
			else if (eco==null)
				;
			else if (opening==null)
				opening = eco;
			else
				opening = opening+" "+eco;

			Date date = res.getDate(15/*GameDate*/);
			String date_string = "";
			if (date!=null) {
				int dateFlags = res.getInt(18/*DateFlags*/);
				PgnDate pgnDate = new PgnDate(date,(short)(dateFlags & 0x00ff));
				date_string = pgnDate.toLocalDateString(true);
			}

      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((row_style));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((res.getString(3/*Idx*/)));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((white_name));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((white_elo));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((black_name));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((black_elo));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((PgnUtil.resultString(res.getInt(10/*Result*/))));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((event_name));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((site_name));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((round));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((date_string));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((gid));
      out.write(',');
      out.print((row));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((black_name));
      out.write('-');
      out.print((white_name));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((opening));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      
	}

	res.close();

	if (row < max_row) {
		//  end of result set has been reached; count!
		count_results = row;
		//  print some empty lines
		for (int dummy_row=row; dummy_row < max_row; dummy_row++)
		{
			String row_style = ((dummy_row %2)==1) ? "odd":"even";
			
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((row_style));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      
		}
	}

	su.set("count-results", count_results);


      out.write(_jsp_string21, 0, _jsp_string21.length);
       if (!big_search) {
			
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((search.firstPlayerName));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      
 } 
      out.write(_jsp_string24, 0, _jsp_string24.length);
      
	//  page navigation
		int max_page;
		if (count_results>=0) {
			//  number of pages is known
			max_page = (count_results+pagesize-1)/pagesize;
		}
		else {
			//  number of pages is not (yet) known
			max_page = -1;
		}

		if (pagenum <= 6)
		{
				for (int p=1; p < pagenum; p++) {
					
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((p));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((p));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
				}
		}
		else
		{
			for (int p=1; p <= 3; p++) {
					
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((p));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((p));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
			}
			
      out.write(_jsp_string27, 0, _jsp_string27.length);
      
			for (int p=pagenum-2; p < pagenum; p++) {
					
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((p));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((p));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
			}
		}

		if (pagenum > 1) {
			
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(((pagenum-1)));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      
		}

		
      out.write(_jsp_string29, 0, _jsp_string29.length);
      out.print((pagenum));
      out.write(_jsp_string30, 0, _jsp_string30.length);
      

		if (max_page < 1 || pagenum < max_page) {
			
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(((pagenum+1)));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      
		}

		if (max_page >= 1 && (pagenum+5) >= max_page)
		{
			for (int p=pagenum+1; p <= max_page; p++) {
					
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((p));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((p));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
			}
		}
		else if (max_page >= 1)
		{
			for (int p=pagenum+1; p <= (pagenum+2); p++) {
					
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((p));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((p));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
			}
			
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((max_page));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((max_page));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
		}
		else
		{
			//  max_page unknown, print just one more
			
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(((pagenum+1)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(((pagenum+1)));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      
		}

      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((pagesize));
      out.write(_jsp_string35, 0, _jsp_string35.length);
            if (big_search) { 
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((search.firstPlayerName));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      
		}
	} catch (Throwable ex) {
		ex.printStackTrace(response.getWriter());
	} finally {
//		if (stm!=null) stm.close();
		JoConnection.release(conn);
	}

      out.write(_jsp_string38, 0, _jsp_string38.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -8852640556211195023L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("collection.jsp"), 8477643523409829685L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string25;
  private final static char []_jsp_string6;
  private final static char []_jsp_string35;
  private final static char []_jsp_string17;
  private final static char []_jsp_string27;
  private final static char []_jsp_string26;
  private final static char []_jsp_string19;
  private final static char []_jsp_string38;
  private final static char []_jsp_string36;
  private final static char []_jsp_string21;
  private final static char []_jsp_string37;
  private final static char []_jsp_string20;
  private final static char []_jsp_string32;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string16;
  private final static char []_jsp_string31;
  private final static char []_jsp_string33;
  private final static char []_jsp_string18;
  private final static char []_jsp_string3;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string30;
  private final static char []_jsp_string14;
  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string34;
  private final static char []_jsp_string13;
  private final static char []_jsp_string15;
  private final static char []_jsp_string28;
  private final static char []_jsp_string24;
  private final static char []_jsp_string23;
  private final static char []_jsp_string12;
  private final static char []_jsp_string4;
  private final static char []_jsp_string11;
  private final static char []_jsp_string29;
  private final static char []_jsp_string0;
  private final static char []_jsp_string22;
  private final static char []_jsp_string1;
  static {
    _jsp_string25 = "<a href=\"javascript:submit('pagenum',".toCharArray();
    _jsp_string6 = "<img src=\"up8.gif\" title=\"absteigend sortiert\" width=8 height=8 border=0>".toCharArray();
    _jsp_string35 = "\"\r\n			><input type=image src=\"border-right.gif\" alt=\"\" class=\"srchimgs\" align=\"absbottom\" border=\"0\" height=\"18\" width=\"9\">\r\n				Zeilen\r\n			</td></tr></table>\r\n		</td>\r\n	</tr>\r\n".toCharArray();
    _jsp_string17 = "\r\n			</a>\r\n		</td>\r\n		<td class=\"center\">\r\n			<a href=\"javascript:frame(".toCharArray();
    _jsp_string27 = " ... ".toCharArray();
    _jsp_string26 = "</a>&nbsp;".toCharArray();
    _jsp_string19 = "<tr class=\"".toCharArray();
    _jsp_string38 = "\r\n</table>\r\n</form>\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string36 = "\r\n	<tr class=footer><td colspan=11>\r\n		<table>\r\n			<tr><td>Player1</td><td><input name=\"firstPlayerName\" value=\"".toCharArray();
    _jsp_string21 = "\r\n	<tr class=\"footer\">\r\n		<td colspan=11>\r\n			<table cellspacing=0 cellpadding=0><tr><td width=\"180px\">\r\n			<!--short search-->\r\n			<input type=image name=ignore3 width=0 height=0>\r\n			<img type=image name=\"more-search\" src=\"border-search.gif\" alt=\"\" class=\"srchimgs\" align=\"absbottom\" border=\"0\" height=\"18\" width=\"16\"\r\n>".toCharArray();
    _jsp_string37 = "\"></td></tr>\r\n		</table>\r\n	</td></tr>\r\n".toCharArray();
    _jsp_string20 = "\"><td colspan=11>&nbsp;</td></tr>".toCharArray();
    _jsp_string32 = " ... <a href=\"javascript:submit('pagenum',".toCharArray();
    _jsp_string7 = "</a>\r\n		</th>\r\n		<th>\r\n			<a href=\"javascript:submit('sort',".toCharArray();
    _jsp_string10 = "</a>\r\n	</th>\r\n	</tr>\r\n\r\n".toCharArray();
    _jsp_string16 = "\r\n			</a>\r\n		</td>\r\n		<td class=\"right\">\r\n			<a href=\"javascript:frame(".toCharArray();
    _jsp_string31 = ")\">&nbsp;&nbsp;<img src=\"right8.gif\" border=0 title=\"n\u00e4chste Seite\"\r\n		                                               align=\"baseline\">&nbsp;&nbsp;</a>&nbsp;".toCharArray();
    _jsp_string33 = "</a>&nbsp;...&nbsp;".toCharArray();
    _jsp_string18 = "\r\n			</a>\r\n		</td>\r\n	</tr>\r\n".toCharArray();
    _jsp_string3 = ")\">".toCharArray();
    _jsp_string8 = ")\">ELO&nbsp;".toCharArray();
    _jsp_string2 = "\">\r\n\r\n<table cellspacing=\"0\">\r\n	<tr class=\"header\">\r\n		<th>\r\n			<a href=\"javascript:submit('sort',".toCharArray();
    _jsp_string30 = "\"\r\n			><input type=image src=\"border-right.gif\" alt=\"\" class=\"srchimgs\" name=\"ignore2\"\r\n				align=\"absbottom\" border=\"0\" height=\"18\" width=\"9\">&nbsp;".toCharArray();
    _jsp_string14 = "\">\r\n			".toCharArray();
    _jsp_string9 = "</a>\r\n		</th>\r\n		<th><a href=\"javascript:submit('sort',".toCharArray();
    _jsp_string5 = "<img src=\"down8.gif\" title=\"aufsteigend sortiert\" width=8 height=8 border=0>".toCharArray();
    _jsp_string34 = "\r\n		</td><td style=\"width: 1cm\">&nbsp;</td><td>\r\n			<img src=\"border-left.gif\" alt=\"\" class=\"srchimgs\" align=\"absbottom\" border=\"0\" height=\"18\" width=\"9\"\r\n			><input tabindex=3 name=\"pagesize\" class=\"sbox-page\" value=\"".toCharArray();
    _jsp_string13 = ")\" title=\"".toCharArray();
    _jsp_string15 = "\r\n			</a>\r\n		</td>\r\n		<td>\r\n			<a href=\"javascript:frame(".toCharArray();
    _jsp_string28 = ")\">&nbsp;&nbsp;<img src=\"left8.gif\"\r\n		                                               border=0 title=\"vorherige Seite\" align=\"baseline\">&nbsp;&nbsp;</a>".toCharArray();
    _jsp_string24 = "<input type=image src=\"border-right.gif\" alt=\"\" name=\"ignore1\" class=\"srchimgs\"\r\n			     align=\"absbottom\" border=\"0\" height=\"18\" width=\"9\">\r\n		</td>\r\n		<td>Seite&nbsp;\r\n".toCharArray();
    _jsp_string23 = "\">".toCharArray();
    _jsp_string12 = "\">\r\n		<td class=\"right\">\r\n			<a href=\"javascript:frame(".toCharArray();
    _jsp_string4 = "&nbsp;".toCharArray();
    _jsp_string11 = "\r\n\r\n	<tr class=\"".toCharArray();
    _jsp_string29 = "<img src=\"border-left.gif\" alt=\"\" class=\"srchimgs\" align=\"absbottom\" border=\"0\" height=\"18\" width=\"9\"\r\n			><input class=\"sbox-page\" name=\"pagenum\" tabindex=2 value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<html>\r\n<head>\r\n	<title>jose Web Interface</title>\r\n	<style>\r\n		td,th,input { font-family: Arial,Helvetica,Sans-Serif; font-size: 14px; }\r\n		TR.odd {  background-color: #e2e2ff;}\r\n		TR.even {  background-color: #eeeeff; }\r\n		TD { padding:2 4 2 4; white-space: nowrap; }\r\n		TD.center { text-align: center; }\r\n		TD.right { text-align: right; }\r\n		TR.header, TR.footer {  background-color: #e5e5e5; padding: 8 4 8 4; }\r\n		A { color:black; text-decoration: none; }\r\n		SELECT.footer { background-color: #e5e5e5 }\r\n\r\n		input.sbox-search {\r\n			color: black; width: 120px; height: 18px; border: 0;\r\n			background: white url(border-background.gif) repeat-x left top;\r\n			padding-top: 1px; padding-left: 3px; padding-right: 3px; padding-bottom: 0px;\r\n		}\r\n		input.sbox-page {\r\n			color: black; height: 17px; border: 0;\r\n			background: white url(border-background.gif) repeat-x left top;\r\n			padding: 2px; text-align: center; width: 24px;\r\n		}\r\n\r\n		select.sbox-rows {\r\n			color: black; height: 17px; border: none;\r\n			background: white url(border-background.gif) repeat-x left top;\r\n			padding: 2px;\r\n		}\r\n	</style>\r\n</head>\r\n".toCharArray();
    _jsp_string22 = "<input name=\"firstPlayerName\" class=\"sbox-search\" tabindex=1\r\n			     value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n<body>\r\n\r\n<script language=\"JavaScript\">\r\n	function submit(param,value)\r\n	{\r\n		var form = document.forms[1];\r\n		form.elements[param].value = value;\r\n		form.submit();\r\n	}\r\n	function frame(gid,row)\r\n	{\r\n		var form = document.forms[0];\r\n		form.elements['GId'].value = gid;\r\n		form.elements['row'].value = row;\r\n		form.submit();\r\n	}\r\n</script>\r\n\r\n<form method=\"post\" action=\"frame.jsp\">\r\n	<input type=\"hidden\" name=\"GId\">\r\n	<input type=\"hidden\" name=\"row\">\r\n</form>\r\n\r\n<form method=\"post\">\r\n<input type=\"hidden\" name=\"sort\" value=\"".toCharArray();
  }
}
