/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _res;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import de.jose.Version;
import java.sql.Connection;
import de.jose.db.JoConnection;
import de.jose.pgn.Collection;
import de.jose.db.JoPreparedStatement;
import java.sql.ResultSet;
import de.jose.web.WebApplication;

public class _snoop__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
       WebApplication.open(application,response); 
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((Version.jose));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((Version.osName));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((Version.osVersion));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((Version.arch));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((WebApplication.theApplication.theWorkingDirectory));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((WebApplication.theApplication.theDatabaseId));
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((WebApplication.theApplication.theDatabaseDirectory));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      
	JoConnection conn = null;
	try {
		conn = JoConnection.get();
		JoPreparedStatement stm = conn.getPreparedStatement(
				"SELECT Id, Name, GameCount" +
				" FROM Collection WHERE GameCount > 0");
		stm.execute();
		while (stm.next())
		{
			
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((stm.getInt(1)));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((stm.getString(2)));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((stm.getInt(3)));
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      
		}
	} catch (Throwable ex) {
			ex.printStackTrace(response.getWriter());
	} finally {
		JoConnection.release(conn);
	}


      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_snoop__jsp.java", "/res/snoop.jsp");
    _caucho_line_map.add(8, 1);
    _caucho_line_map.add(1, 33);
    _caucho_line_map.add(10, 41);
    _caucho_line_map.add(16, 43);
    _caucho_line_map.add(17, 45);
    _caucho_line_map.add(17, 47);
    _caucho_line_map.add(17, 49);
    _caucho_line_map.add(21, 51);
    _caucho_line_map.add(24, 53);
    _caucho_line_map.add(36, 57);
    _caucho_line_map.add(47, 69);
    _caucho_line_map.add(48, 71);
    _caucho_line_map.add(49, 73);
    _caucho_line_map.add(50, 75);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("res/snoop.jsp"), 1129044818000L, 1395L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string4;
  private static byte []_jsp_string10;
  private static byte []_jsp_string6;
  private static byte []_jsp_string3;
  private static byte []_jsp_string8;
  private static byte []_jsp_string2;
  private static byte []_jsp_string12;
  private static byte []_jsp_string7;
  private static byte []_jsp_string1;
  private static byte []_jsp_string9;
  private static byte []_jsp_string11;
  private static byte []_jsp_string0;
  private static byte []_jsp_string5;
  static {
    _jsp_string4 = " ".getBytes();
    _jsp_string10 = "</td>\r\n			<td>".getBytes();
    _jsp_string6 = "\r\n\r\n<hr>\r\nDatabase is: ".getBytes();
    _jsp_string3 = " <br>\r\nrunning on ".getBytes();
    _jsp_string8 = "\r\n\r\n<hr>\r\n\r\n<table border=1>\r\n	<tr>\r\n		<th>Id</th>\r\n		<th>Name</th>\r\n		<th># of Games</th>\r\n	</tr>\r\n".getBytes();
    _jsp_string2 = "\r\n\r\n<html>\r\n<head></head>\r\n\r\n<body>\r\nHello from jose ".getBytes();
    _jsp_string12 = "\r\n</table>\r\n\r\n</body>\r\n</html>".getBytes();
    _jsp_string7 = "\r\n<br>\r\non ".getBytes();
    _jsp_string1 = "\r\n\r\n".getBytes();
    _jsp_string9 = "<tr>\r\n			<td>".getBytes();
    _jsp_string11 = "</td>\r\n			</tr>".getBytes();
    _jsp_string0 = "\r\n".getBytes();
    _jsp_string5 = "\r\n\r\n<hr>\r\n\r\nWorking directory is: ".getBytes();
  }
}
