<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title> The Game Panel </title>
	<meta name="help" content="window.game">
	
	<!--@css--><link rel="StyleSheet" type="text/css" href="../../manual.css"><!--/@css-->
</head>

<body>

<!--@header--><table width="100%">
<tr>
<td align=left>
<a href="04-game.html"><img src="../../img/previous.gif" width="30" height="30" alt="Previous Page" border="0"></a>
<a href="04-game.html"><img src="../../img/up.gif" width="30" height="30" alt="Chapter" border="0"></a>
<a href="04-game.html"><img src="../../img/next.gif" width="30" height="30" alt="Next Page" border="0"></a>
</td>

<td align=left class=header> <font class="logo">jose</font> &nbsp; 1.3 </td>
<td align=right>
<a href="../../index.html"><img src="../../img/book.gif" width="30" height="30" alt="Manual" border="0"></a>
<a href="../../manindex.html"><img src="../../img/index.gif" width="30" height="30" alt="Index" border="0"></a>
<a href="mailto:jose-chess@sourceforge.net"><img src="../../img/mail.gif" width="30" height="30" alt="Feedback" border="0"></a>
</td>
</tr>
</table>
<hr><!--/@header-->

<h1>The Game Panel</h1>

<p>This panel shows the text of games, along with variations and user comments.<br><br>

<img src="shot0104.jpg" width="359" height="413" alt="" border="0">

<h2>Tabs</h2>

<p>Use the tabs on top of the panel to switch between games. 
Use the "x" button at the right to close a tab. Or right click on a tab to see more options.
<p>Modified games are indicated by a small pencil icon.</p>

<h2>Enter Moves</h2>

<p>You can use this panel to enter moves with the keyboard:<br>
<img src="shot0110.jpg" width="143" height="64" alt="" border="0"><br>
Type the move, then hit "Return" to execute it. <br>
Text that does not resemble a move, will be interpreted as a textual comment.
</p>

<h2>Navigation</h2>

<p>You can use <!--@see:menu.game-->&#32; <a href="../../04-menu/03-game.html">Game Menu</a> &#32;<!--/@see--> or the toolbar on top of the board window to navigate within a game.<br>
Click on a move to immediately navigate to a certain position.</p>

<h2>Editing Comments</h2>

<p>To create a text comment, place the caret (the text cursor) after the desired move and just start typing.
Note that you can edit commentary text between moves, but you can not directly edit the moves.

<p>Game details, like player names, event, etc., can also be edited. 
Or use <!--@see:menu.game.details-->&#32; <a href="../../04-menu/03-game.html#menu.game.details">Details...</a> &#32;<!--/@see-->.

<h2>Context Menu</h2>

<p><img src="shot0106.jpg" width="243" height="227" alt="" border="0"></p>

<!--@toc3:menu.game.close.ref1:menu.game.close--><a name="menu.game.close.ref1">
<h3>Close</h3><!--/@toc3-->

<p>Closes the current game. (see <!--@see:menu.game.close-->&#32; <a href="../../04-menu/03-game.html#menu.game.close">Close</a> &#32;<!--/@see-->).</p>
</a>

<!--@toc3:menu.game.close.all.but.ref1:menu.game.close.all.but--><a name="menu.game.close.all.but.ref1">
<h3>Close All But This</h3><!--/@toc3-->

<p>Closes all tabs except the current (see <!--@see:menu.game.close.all.but-->&#32; <a href="../../04-menu/03-game.html#menu.game.close.all.but">Close All But This</a> &#32;<!--/@see-->).</p>
</a>

<!--@toc3:menu.game.close.all.ref1:menu.game.close.all--><a name="menu.game.close.all.ref1">
<h3>Close All</h3><!--/@toc3-->

<p>Closes all tabs (see <!--@see:menu.game.close.all-->&#32; <a href="../../04-menu/03-game.html#menu.game.close.all">Close All</a> &#32;<!--/@see-->).</p>
</a>

<!--@toc3:tab.layout--><a name="tab.layout">
<h3>Tab Layout</h3><!--/@toc3-->

<p>Choose the tab layout:</p>
<ul>
<li><b><!--@lang:tab.layout.scroll-->Scroll<!--/@lang--></b> shows all tabs in one row. Use the arrow buttons at the right to scroll through the tabs.</li>
<li><b><!--@lang:tab.layout.wrap-->Wrap<!--/@lang--></b> shows the tabs in multiple rows. </li>
</ul>

</a>

<!--@toc3:menu.game.details.ref1:menu.game.details--><a name="menu.game.details.ref1">
<h3>Details...</h3><!--/@toc3-->

<p>Opens the <!--@see:dialog.game.details-->&#32; <a href="../../05-dialog/03-game.html">The Game Details Dialog</a> &#32;<!--/@see--> to edit player names, event dates, etc.</p>
</a>


<!--@toc2:menu.game.text.incr.ref1:menu.game.text.incr--><a name="menu.game.text.incr.ref1">
<h2>Increase Text Size</h2><!--/@toc2-->
<p>Increase text size in the <!--@see:window.game-->&#32; <a href="04-game.html">The Game Panel</a> &#32;<!--/@see-->. Use <!--@see:dialog.option.tab7-->&#32; <a href="../../05-dialog/02-option/07-styles.html">Text Styles</a> &#32;<!--/@see--> to set font styles ans sizes in detail. </p>

<!--@toc2:menu.game.text.decr.ref1:menu.game.text.decr--><a name="menu.game.text.decr.ref1">
<h2>Decrease Text Size</h2><!--/@toc2-->
<p>Decrease text size in the <!--@see:window.game-->&#32; <a href="04-game.html">The Game Panel</a> &#32;<!--/@see-->. Use <!--@see:dialog.option.tab7-->&#32; <a href="../../05-dialog/02-option/07-styles.html">Text Styles</a> &#32;<!--/@see--> to set font styles ans sizes in detail. </p>


<!--@toc3:menu.file.save.ref1:menu.file.save--><a name="menu.file.save.ref1">
<h3>Save</h3><!--/@toc3-->

<p>Save the current game to the database if it was modified (see <!--@see:menu.file.save-->&#32; <a href="../../04-menu/01-file.html#menu.file.save">Save</a> &#32;<!--/@see-->).</p>
</a>

<!--@toc3:menu.file.revert.ref1:menu.file.revert--><a name="menu.file.revert.ref1">
<h3>Revert Game</h3><!--/@toc3-->

<p>Revert to the saved game (see <!--@see:menu.file.revert-->&#32; <a href="../../04-menu/01-file.html#menu.file.revert">Revert Game</a> &#32;<!--/@see-->). </p>
</a>

<!--@toc3:doc.menu.annotate--><a name="doc.menu.annotate">
<h3>Annotate</h3><!--/@toc3-->

<p>Add a move annotation. Choose an annotaion from the menu.
Note that you also can enter these annotaion from the keyboard. </p>

<p>Open <!--@see:window.toolbar.symbols-->&#32; <a href="05-symbols.html">The Annotation Panel</a> &#32;<!--/@see--> to open a window with a list of 
available annotations.</p>
</a>

<!--@toc3:pgn.nag.250--><a name="pgn.nag.250">
<h3>Diagram</h3><!--/@toc3-->

<p>Insert a diagram after the current move. </p>
</a>

<!--@toc3:doc.menu.line.cut--><a name="doc.menu.line.cut">
<h3>Cut Off Line</h3><!--/@toc3-->

<p>Delete the rest of this line. Use with care !</p>
</a>

<!--@toc3:doc.menu.line.delete--><a name="doc.menu.line.delete">
<h3>Delete Line</h3><!--/@toc3-->

<p>Delete this line. Use with care !</p>
</a>

<!--@toc3:doc.menu.delete.comment--><a name="doc.menu.delete.comment">
<h3>Delete Comment</h3><!--/@toc3-->

<p>Delete this comment or diagram.</p>
</a>

<!--@toc3:doc.menu.line.uncomment--><a name="doc.menu.line.uncomment">
<h3>Delete All Comments</h3><!--/@toc3-->

<p>Remove all comments from this line.</p>
</a>

<!--@toc3:doc.menu.line.promote--><a name="doc.menu.line.promote">
<h3>Promote Line</h3><!--/@toc3-->

<p>When clicking in a variation line: make this line the main line.
The current main line will become a variation line.
</p>
</a>

<!--@toc3:menu.edit.copy.pgn--><a name="menu.edit.copy.pgn">
<h3>Copy PGN</h3><!--/@toc3-->
<p>Copy the text of the current game to the system clipboard.<br>
The text will be copied as PGN (Portable Game Notation: a common format that is understood by most other chess applications).
</p>

<!--@toc3:menu.edit.paste.pgn--><a name="menu.edit.paste.pgn">
<h3>Paste PGN</h3><!--/@toc3-->
<p>Paste a PGN file from the system clipboard.<br>
Note that you must take care that the clipboard contains a valid PGN file. Otherwise you will not see a useful result...
</p>

<!--@toc3:menu.edit.ecofy.ref2:menu.edit.ecofy--><a name="menu.edit.ecofy.ref2">
<h3>Classify ECO</h3><!--/@toc3-->
<p>Update the opening classification of the current game. See <!--@see:menu.edit.ecofy-->&#32; <a href="../../04-menu/02-edit.html#menu.edit.ecofy">Classify ECO</a> &#32;<!--/@see-->. </p>

<!--@toc3:move.format--><a name="move.format">
<h3>Notation</h3><!--/@toc3-->

<p><img src="shot0105.jpg" width="364" height="236" alt="" border="0"><br>

Choose the display format for moves:</p>
<ul>
<li><!--@lang:move.format.short-->Short<!--/@lang--></li>
<li>